Corrected sum
js-tasks-ru/jsbasic-20201113_epik56 pull request #1
Opened 2020-11-14 08:23 UTC by ManTi56

done

2020-11-14 08:31 UTC, jsru commented
Поздравляю, все задачи решены абсолютно верно
```diff
Первая задача
+ 1+1=2
```

Добавляю преподавателя (@koalex) для код-ревью, посмотрим что он скажет :)

2020-11-20 13:06 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-11-20 14:07 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Первая задача
+ 1+1=2
```
```diff
Вычислить факториал
+ факториал 5 равен 120 
+ факториал 0 равен 1
+ факториал 3 равен 6 
+ факториал 1 равен 1
```
```diff
Допишите функцию валидации имени пользователя
- если имя корректное, то true
- если меньше 4 символов то false
- если содержит пробелы, то false
```

2020-11-21 13:23 UTC, koalex approved these changes

2020-11-21 13:23 UTC, jsru commented
PR не может быть принят, обратитесь, пожалуйста, к преподавателю.

2020-11-21 13:24 UTC, koalex requested changes
@ManTi56 проверь чтобы `npm test` не выдавал ошибок

2020-11-23 11:30 UTC, koalex approved these changes

2020-11-23 11:30 UTC, jsru commented
PR не может быть принят, обратитесь, пожалуйста, к преподавателю.

2020-11-23 11:56 UTC, koalex approved these changes

2020-11-23 11:56 UTC, jsru commented
PR не может быть принят, обратитесь, пожалуйста, к преподавателю.

2020-11-23 12:33 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

```diff
Допишите функцию валидации имени пользователя
- если содержит пробелы, то false
- если имя корректное, то true
- если меньше 4 символов то false
```
```diff
Вычислить факториал
+ факториал 1 равен 1
+ факториал 0 равен 1
+ факториал 5 равен 120 
+ факториал 3 равен 6 
```
```diff
Сделать первый символ заглавным
- должна работать для пустой строки
- должна делать первый символ заглавным
- должна работать для строки из одной буквы
```
```diff
Первая задача
+ 1+1=2
```

2020-11-23 13:20 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-11-23 14:40 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @koalex

2020-11-23 14:57 UTC, koalex approved these changes

2020-11-23 14:58 UTC, merged